# Generated by Django 5.0.6 on 2026-08-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
