# Generated by Django 5.0.6 on 2026-08-20 13:32

import verifications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='verifications/', validators=[verifications.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/', validators=[verifications.validators.validate_selfie_image]),
        ),
    ]
