# Generated by Django 5.0.6 on 2026-08-18 23:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='never_married', max_length=20)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('income_range', models.CharField(blank=True, max_length=50)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(default='India', max_length=100)),
                ('about_me', models.TextField(blank=True, max_length=1000)),
                ('tamil_language_importance', models.CharField(choices=[('very', 'Very Important'), ('somewhat', 'Somewhat Important'), ('not', 'Not Important')], default='somewhat', max_length=20)),
                ('festivals', models.JSONField(blank=True, default=list)),
                ('spiritual_orientation', models.CharField(choices=[('temple_going', 'Temple-going'), ('spiritual_not_religious', 'Spiritual but not religious'), ('cultural_only', 'Cultural only'), ('atheist', 'Atheist')], default='cultural_only', max_length=50)),
                ('diet', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian'), ('vegan', 'Vegan')], default='vegetarian', max_length=20)),
                ('family_involvement', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='moderate', max_length=20)),
                ('relocation_willingness', models.CharField(choices=[('within_tn', 'Within Tamil Nadu'), ('within_india', 'Within India'), ('abroad', 'Abroad'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('subcaste', models.CharField(blank=True, max_length=100, null=True)),
                ('gothram', models.CharField(blank=True, max_length=100, null=True)),
                ('natchathiram', models.CharField(blank=True, max_length=100, null=True)),
                ('rasi', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('is_approved_by_individual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manages_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_managers', to='profiles.individualprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='profiles.individualprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='profiles.parentprofile')),
            ],
        ),
    ]
