# Generated by Django 5.0.6 on 2026-08-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
