# Generated by Django 5.0.6 on 2026-08-20 13:32

import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_individualprofile_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='profile_photos/', validators=[profiles.validators.validate_image_file]),
        ),
    ]
