# Generated by Django 5.0.6 on 2026-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='photo_visibility',
            field=models.CharField(choices=[('private', 'Private until mutual interest'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='preferred_age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='preferred_age_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='preferred_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='preferred_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='who_can_message',
            field=models.CharField(choices=[('all', 'All users'), ('matches', 'Only matches')], default='matches', max_length=20),
        ),
    ]
